server:
  port: 8085
  servlet:
    context-path:
mybatis:
  type-aliases-package: com.newer.hotelmanage.domain
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost/hhhh?useLL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
  session:
    store-type: redis
  jackson:
    serialization:
      indent_output: true
logging:
  level:
    com.newer.hotelmanage.mapper: debug #\u8F93\u51FAdebug\u7EA7\u522B\u5373\u4EE5\u4E0A\u7EA7\u522B\u7684\u65E5\u5FD7


jwt:
  secret: mySecret #\u81EA\u5B9A\u4E49\u7684\u79C1\u94A5
  expiration: 3600   #token\u7684\u8FC7\u671F\u65F6\u95F4
  header: Authorization #\u5B9A\u4E49\u8BF7\u6C42\u5934\u90E8\u4E2D\u7684\u81EA\u5B9A\u4E49\u5C5E\u6027\u540D\u79F0
  tokenHead: Bearer #\u627F\u63A5\u5B57\u7B26\u4E32
  path : /auth  #controller\u4E2D\u7684\u8BF7\u6C42\u8DEF\u5F84 \u767B\u9646
  refresh: /refresh #controller\u4E2D\u7684\u8BF7\u6C42\u8DEF\u5F84 \u5237\u65B0